language: python 

python:
  matrix:
    include:
      - "3.5"
      - "3.6"
      - "3.7"
        dist: xenial

cache: pip 

before_install: 
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov 
  - python setup.py install

install:
  - pip install -r requirements.txt
  - pip install  . 

script: pytest TestDatpiff.py

