language: python 

python: 
    - 3.7


before_install: 
  - pip install -U pip
  - python setup.py install
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - pip install  pytest
  - pip install nose 
  - pip install codecov 

install:
  - pip install -r requirements.txt
  - pip install -e . 
  - pip install ".[test]" .

script:  
  - pytest
#- "nosetests --with-coverage --cover-package Datpiff"

#"python setup.py develop && nosetests -w tests/"
#
#iscript:  python -m pytest -m 
#
after_success: 
  - codecov



