language: python 

python:
  - "3.7"

cache: pip 

before_install: 
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov 

install:
  - pip install -r requirements.txt
  - pip install ".[test]" . 

script: pytest TestDatpiff.py

