language: python 

matrix:
    include:
        - python: "3.5"
        - python: "3.6"
        - python: "3.7"
            dist: xenial


cache: pip 

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

before_install: 
  - pip install -U pip
  - python setup.py install
  - pip install  pytest
  - pip install codecov 

install:
  - pip install -r requirements.txt
  - pip install -e . 
  - pip install ".[test]" .

script: 
    - pytest tests/test_src/test_mixtapes.py 

after_success: 
  - codecov



